CREATE DATABASE inlock_games_manha;
GO

USE inlock_games_manha;
GO

CREATE TABLE ESTUDIO(
	idEstudio INT PRIMARY KEY IDENTITY(1,1),
	nomeEstudio VARCHAR(30)
);
GO

CREATE TABLE JOGO(
	idJogo INT PRIMARY KEY IDENTITY(1,1),
	nomeJogo VARCHAR(30) NOT NULL UNIQUE,
	descricao VARCHAR(200) NOT NULL UNIQUE,
	dataLancamento DATE NOT NULL,
	valor SMALLMONEY NOT NULL,
	idEstudio INT FOREIGN KEY REFERENCES ESTUDIO(idEstudio)
);
GO

CREATE TABLE TIPOUSUARIO(
	idTipoUsuario INT PRIMARY KEY IDENTITY(1,1),
	titulo VARCHAR(20) NOT NULL,
);
GO

CREATE TABLE USUARIO(
	idUsuario INT PRIMARY KEY IDENTITY(1,1),
	email VARCHAR(40) NOT NULL UNIQUE,
	senha VARCHAR(20) NOT NULL,
	idTipoUsuario INT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario)
);
GO
